# Generated by Django 5.1 on 2024-08-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_salaries', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_etudiants', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_employes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['email'], name='etablisseme_email_a45d2d_idx'), models.Index(fields=['telephone'], name='etablisseme_telepho_53f017_idx')],
            },
        ),
    ]
