# Generated by Django 5.1 on 2024-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Etablissement/logo'),
        ),
    ]
