# Generated by Django 5.1 on 2024-08-20 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='libelle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classe',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissement.etablissement'),
        ),
        migrations.DeleteModel(
            name='Libelle',
        ),
    ]
