# Generated by Django 5.1 on 2024-08-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceAFournirPourInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.anneeacademique",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.classe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceFourniesPourInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en cours", "en cours"),
                            ("acceptée", "Pièce acceptée"),
                            ("rejetée", "Pièce rejetée"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fichier", models.FileField(upload_to="Fichiers/PieceInscription")),
                (
                    "incription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.inscription",
                    ),
                ),
                (
                    "piece_a_fournir_pour_inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.pieceafournirpourinscription",
                    ),
                ),
            ],
        ),
    ]
