# Generated by Django 5.1 on 2024-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_classe_libelle_alter_classe_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['-nom', '-prenom'], 'verbose_name': 'Étudiant(e)', 'verbose_name_plural': 'Les étudiants'},
        ),
        migrations.AlterModelManagers(
            name='etudiant',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='username',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
