# Generated by Django 5.1 on 2024-08-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_alter_etudiant_options_alter_etudiant_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
