# Generated by Django 5.1 on 2024-08-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inscription", "0003_alter_etudiant_options_alter_etudiant_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("coefficient", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("debut", models.DateField()),
                ("fin", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("credits", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_attribuee", models.DateField()),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="inscription.etudiant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="note.matiere",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matiere",
            name="unite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="note.unite",
            ),
        ),
        migrations.CreateModel(
            name="UniteClasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unite_classes",
                        to="inscription.classe",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unite_classes",
                        to="note.semestre",
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unite_classes",
                        to="note.unite",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="unite",
            name="classes",
            field=models.ManyToManyField(
                related_name="unites",
                through="note.UniteClasse",
                to="inscription.classe",
            ),
        ),
    ]
