# Generated by Django 5.1 on 2024-08-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_etudiant_matricule'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniteclasse',
            name='description',
        ),
        migrations.AddField(
            model_name='uniteclasse',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Année', to='inscription.anneeacademique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unite',
            name='credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='uniteclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classe', to='inscription.classe'),
        ),
        migrations.AlterField(
            model_name='uniteclasse',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Semestre', to='note.semestre'),
        ),
        migrations.AlterField(
            model_name='uniteclasse',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unité', to='note.unite'),
        ),
    ]
