# Generated by Django 5.1 on 2024-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_uniteclasse_description_uniteclasse_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='fin',
        ),
    ]
