# Generated by Django 5.1 on 2024-08-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_etudiant_matricule'),
        ('note', '0004_remove_unite_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='classes',
            field=models.ManyToManyField(related_name='unites', through='note.UniteClasse', to='inscription.classe'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_attribuee',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Etudiant', to='inscription.etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matiere', to='note.matiere'),
        ),
    ]
