# Generated by Django 5.1 on 2024-08-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_etudiant_matricule'),
        ('note', '0005_unite_classes_alter_note_date_attribuee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscription.anneeacademique'),
            preserve_default=False,
        ),
    ]
