# Generated by Django 5.1 on 2024-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Cahier de Texte',
                'verbose_name_plural': 'Les cahiers de texte',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'verbose_name_plural': 'Les emplois du temps',
                'ordering': ['-jour', '-tranche_horaire'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Les enseignants',
                'ordering': ['-nom', '-prenom'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Les grades',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('volume_horaire', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Les matières',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_obtenue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_evaluation', models.DateField()),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Les notes',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='PresenceEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Présence Étudiant',
                'verbose_name_plural': 'Les présences étudiants',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Les semestres',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='TrancheHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tranche Horaire',
                'verbose_name_plural': 'Les tranches horaires',
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Les unités',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='UniteClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unité de Classe',
                'verbose_name_plural': 'Les unités de classe',
                'ordering': ['-libelle'],
            },
        ),
    ]
