# Generated by Django 5.1 on 2024-08-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inscription", "0002_pieceafournirpourinscription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("matricule", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Les enseignants",
                "ordering": ["-nom", "-prenom"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Les grades",
                "ordering": ["-libelle"],
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
                ("volume_horaire", models.IntegerField()),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Les matières",
                "ordering": ["-libelle"],
            },
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Les semestres",
                "ordering": ["-libelle"],
            },
        ),
        migrations.CreateModel(
            name="TrancheHoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.TimeField()),
                ("fin", models.TimeField()),
                ("libelle", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tranche Horaire",
                "verbose_name_plural": "Les tranches horaires",
                "ordering": ["-debut"],
            },
        ),
        migrations.CreateModel(
            name="Unite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Unité",
                "verbose_name_plural": "Les unités",
                "ordering": ["-libelle"],
            },
        ),
        migrations.CreateModel(
            name="EmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=20)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.classe",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emploidutemps.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emploidutemps.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emploi du Temps",
                "verbose_name_plural": "Les emplois du temps",
                "ordering": ["-jour", "-tranche_horaire"],
            },
        ),
        migrations.CreateModel(
            name="CahierTexte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date", models.DateField()),
                (
                    "emploi_du_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emploidutemps.emploidutemps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cahier de Texte",
                "verbose_name_plural": "Les cahiers de texte",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="enseignant",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="emploidutemps.grade"
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_obtenue", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_evaluation", models.DateField()),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.etudiant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emploidutemps.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Les notes",
                "ordering": ["-date_evaluation"],
            },
        ),
        migrations.CreateModel(
            name="PresenceEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("presence", models.BooleanField(default=False)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence Étudiant",
                "verbose_name_plural": "Les présences étudiants",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="presence_etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="emploidutemps.presenceetudiant",
            ),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="tranche_horaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="emploidutemps.tranchehoraire",
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="unite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="emploidutemps.unite"
            ),
        ),
        migrations.CreateModel(
            name="UniteClasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emploidutemps.semestre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unité de Classe",
                "verbose_name_plural": "Les unités de classe",
                "ordering": ["-libelle"],
            },
        ),
        migrations.AddField(
            model_name="unite",
            name="unite_classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="emploidutemps.uniteclasse",
            ),
        ),
    ]
