# Generated by Django 5.1 on 2024-08-20 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emploidutemps', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.classe'),
        ),
        migrations.AddField(
            model_name='cahiertexte',
            name='emploi_du_temps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.emploidutemps'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.enseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.grade'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.matiere'),
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.etudiant'),
        ),
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.matiere'),
        ),
        migrations.AddField(
            model_name='presenceetudiant',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.etudiant'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='presence_etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.presenceetudiant'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='tranche_horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.tranchehoraire'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.unite'),
        ),
        migrations.AddField(
            model_name='uniteclasse',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.semestre'),
        ),
        migrations.AddField(
            model_name='unite',
            name='unite_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploidutemps.uniteclasse'),
        ),
    ]
