# Generated by Django 5.1 on 2024-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploidutemps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidutemps',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='presence_etudiant',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='tranche_horaire',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='note',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='note',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='presenceetudiant',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='uniteclasse',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='unite_classe',
        ),
        migrations.DeleteModel(
            name='CahierTexte',
        ),
        migrations.DeleteModel(
            name='EmploiDuTemps',
        ),
        migrations.DeleteModel(
            name='TrancheHoraire',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='PresenceEtudiant',
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
        migrations.DeleteModel(
            name='Unite',
        ),
        migrations.DeleteModel(
            name='UniteClasse',
        ),
    ]
