# Generated by Django 5.1 on 2024-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='nbre_heure_effectue',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
