# Generated by Django 5.1 on 2024-09-10 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_vacation_nbre_heure_effectue'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='prix_unitaire_horaire',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
